CREATE TABLE employee_account (
    id INT IDENTITY(1,1) PRIMARY KEY,
    account_type TINYINT NOT NULL,
    account VARCHAR(20) NOT NULL,
    password VARCHAR(20) NOT NULL,
    name NVARCHAR(20) NOT NULL,
    tel VARCHAR(20),
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(50) NOT NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    picture VARBINARY(MAX),
    sex CHAR(1) NOT NULL,
    start_date DATE NOT NULL,
    sick_leave_hours INT,
    personal_leave_hours INT,
    annual_leave_hours INT,
    bereavement_leave_hours INT,
    marriage_leave_hours INT,
    maternal_leave_hours INT,
    paternity_leave_hours INT,
    menstrual_leave_hours INT,
    official_leave_hours INT,
    team_leader_id INT NOT NULL,
    branch TINYINT NOT NULL,
    end_date DATE
);
