CREATE TABLE preference_list (
    id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    select_name NVARCHAR(20) NOT NULL,
    production_year INT NOT NULL,
    price DECIMAL NOT NULL,
    milage INT NOT NULL,
    score INT NOT NULL,
    member_id INT NOT NULL,
    model_id INT,
    brand TINYINT,
    suspension TINYINT,
    door TINYINT,
    passenger TINYINT,
    rear_wheel TINYINT,
    gasoline TINYINT,
    transmission TINYINT,
    cc TINYINT,
    hp INT,
    torque FLOAT,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    preferences_lists TINYINT NOT NULL
);
